version: 2.1
jobs:
  build:
    working_directory: ~/collection-editor
    docker:
      - image: circleci/node:9.0.0
        environment:
           version_number: $CIRCLE_BRANCH
     
    steps:
      - checkout:
          path: ~/collection-editor
      
      - restore_cache:
          key: ce-dependency-cache-{{ checksum "package.json" }}
       
      - run:
          name: clone plugins
          command: |
            if [ -z $CIRCLE_PR_NUMBER ]; then
            target_branch=$CIRCLE_BRANCH
            git clone https://github.com/project-sunbird/sunbird-content-plugins.git plugins -b $target_branch
            else
            prdata=$(curl -X GET -u $GITHUB_USER_TOKEN:x-oauth-basic https://api.github.com/repos/project-sunbird/sunbird-collection-editor/pulls/$CIRCLE_PR_NUMBER)
            target_branch=$(echo "${prdata}" | jq -r '.base.ref')
            git clone https://github.com/project-sunbird/sunbird-content-plugins.git plugins -b $target_branch
            fi
      - run: sudo npm install -g bower@1.8.0 grunt-cli@1.2.0 gulp@3.9.1 codacy-coverage
      - run: npm install
      - run: cd app && bower cache clean --allow-root
      - run: cd app && bower install --force --allow-root
      - run: npm run collection-plugins
      - run: npm run build
      
      - run: 
          name: test-with-coverage
          command: 'npm run test-with-coverage'
      
      - run: mkdir -p /tmp/coverage && cp /home/circleci/collection-editor/coverage/lcov/PhantomJS\ 2.1.1\ \(Linux\ 0.0.0\)/lcov.info /tmp/coverage

      - store_artifacts:
          path: /tmp/coverage
          destination: coverage

      - run:
          name: Install NVM
          command: 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh|bash'
  
      - run:
          name: alter node version
          command: 'source ~/.nvm/nvm.sh && nvm install 8 && nvm use 8 && nvm alias default 8 && node -v'

      - run: 
          name: Install sonar scanner
          command: 'source ~/.nvm/nvm.sh && sudo npm install -g sonarqube-scanner'    
           
      - run: 
          name: Sonar scanner
          command: source ~/.nvm/nvm.sh | sonar-scanner
      - save_cache:
          key: ce-dependency-cache-{{ checksum "package.json" }}
          paths: ./node_modules
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
